import {test,expect} from '@playwright/test';
test('2010: biografia, iPhone, datos y persistencia',async({page})=>{
 await page.route('https://open.spotify.com/embed/**',route=>route.fulfill({contentType:'text/html',body:'<p>Spotify de prueba</p>'}));
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('/?era=2010');
 await expect(page.locator('.app')).toHaveClass(/era-2010/);
 await expect(page.locator('.era-fact-popup,.stories-drawer')).toHaveCount(0);
 await expect(page.locator('.music-card')).toContainText('Get Lucky');
 await page.screenshot({path:'test-results/2010-map.png'});
 await page.getByRole('button',{name:'Abrir reproductor',exact:true}).click();
 await expect(page.locator('.spotify-player')).toHaveAttribute('src',/2lAOYHa5kr9G9eYCNebqWR/);
 await page.getByRole('button',{name:'Pista siguiente'}).click();
 await expect(page.locator('.music-card')).toContainText('Adele');
 await page.getByRole('button',{name:'Ocultar música y detener reproducción'}).click();
 await page.getByRole('button',{name:'La época',exact:true}).click();
 await expect(page.locator('.fact-body')).toContainText('iPhone 4');
 await page.getByRole('button',{name:'Siguiente dato'}).click();
 await expect(page.locator('.fact-body')).toContainText('Curiosity');
 await page.getByRole('button',{name:'Feed',exact:true}).click();
 await expect(page.locator('.feed-post')).toHaveCount(7);
 await page.screenshot({path:'test-results/2010-feed.png'});
 await page.getByRole('button',{name:'Perfil',exact:true}).click();
 await expect(page.locator('.profile-network-cover')).toBeVisible();
 await page.screenshot({path:'test-results/2010-profile.png'});
 await page.getByRole('button',{name:'Publicar un recuerdo',exact:true}).click();
 await page.locator('.memory-map').click({position:{x:650,y:450}});
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.locator('input[name="title"]').fill('Mi recuerdo de 2019');
 await page.locator('input[name="year"]').fill('2019');
 await page.locator('input[name="place"]').fill('Palermo, Buenos Aires');
 await page.locator('textarea').fill('Nos juntamos después de clase para sacar fotos y compartir la merienda junto al lago.');
 await page.getByRole('button',{name:'Guardar recuerdo'}).click();
 await expect(page.locator('.app')).toHaveClass(/view-profile/);
 await expect(page.locator('.personal-counts dd').first()).toHaveText('1');
 await page.reload();
 await page.getByRole('button',{name:'Perfil',exact:true}).click();
 await expect(page.locator('.personal-memory')).toContainText('Mi recuerdo de 2019');
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/2010-mobile.png'});
});
