import type { Decade, Memory } from './types';

// Personas y experiencias ficticias. Los lugares son reales; no se atribuyen
// recitales, estrenos ni acontecimientos históricos a estas coordenadas.
const locations = {
  buenosaires: { place: 'Parque Centenario, Caballito, Buenos Aires', lat: -34.6065, lng: -58.4355 },
  rosario: { place: 'Monumento Nacional a la Bandera, Rosario', lat: -32.9475, lng: -60.6304 },
  cordoba: { place: 'Plaza San Martín, centro de Córdoba', lat: -31.4167, lng: -64.1835 },
  mendoza: { place: 'Lago del Parque General San Martín, Mendoza', lat: -32.8951, lng: -68.8794 },
  mar: { place: 'Plaza Colón, centro de Mar del Plata', lat: -38.0068, lng: -57.5433 },
  bariloche: { place: 'Centro Cívico, San Carlos de Bariloche', lat: -41.1335, lng: -71.3102 },
  salta: { place: 'Plaza 9 de Julio, centro de Salta', lat: -24.7892, lng: -65.4103 },
};
type Seed = [keyof typeof locations, string, number, Memory['category'], string, string];
const scenes: Seed[] = [
  ['buenosaires', 'El walkman de mi hermano en Centenario', 1985, 'Música', 'Leo', 'Fuimos un domingo de septiembre al Parque Centenario, en Caballito. Mi hermano llevaba su walkman en una riñonera y me prestó un auricular mientras dábamos la vuelta al lago. Había grabado canciones de la radio: entre tema y tema se escuchaba al locutor. Nos sentamos en el pasto, compartimos una mandarina y anotamos en la cajita qué canciones queríamos conseguir completas. Cada vez que veo un cassette me acuerdo de esa caminata.'],
  ['rosario', 'La excursión al Monumento a la Bandera', 1983, 'Lugares', 'Clara', 'La seño nos llevó al Monumento a la Bandera, en Rosario, en una salida de cuarto grado. Mi mamá me había preparado dos sanguchitos envueltos en una servilleta y una naranja. Subimos los escalones en fila, buscamos el río entre las columnas y después dibujamos el monumento sentados en nuestros abrigos. En mi dibujo la torre quedó torcida. Todavía está pegado en el cuaderno de ese año.'],
  ['cordoba', 'Una foto frente a la Catedral de Córdoba', 1987, 'Personales', 'Marina', 'Mi papá nos citó en la Plaza San Martín, frente a la Catedral, para empezar las vacaciones con una foto de los cuatro. Mi hermana y yo teníamos el mismo pulóver tejido por la abuela. Cuando levantó la cámara, una paloma pasó tan cerca que nos agachamos. Gastó otra foto, pero al revelar el rollo elegimos la primera: estábamos muertos de risa. Fue nuestra postal familiar de Córdoba.'],
  ['mendoza', 'El mantel a cuadros junto al lago', 1988, 'Acontecimientos', 'Gustavo', 'Festejamos los sesenta de mi abuela al lado del lago del Parque General San Martín, en Mendoza. Mi tío llegó en bicicleta con el pan atado al portaequipaje y mi mamá llevó una torta en una caja de zapatos. Pusimos el mantel a cuadros bajo un árbol y sujetamos las esquinas con cuatro piedras. Cuando sopló las velitas, el viento apagó la mitad antes que ella. La seguimos cargando durante años.'],
  ['mar', 'El final de la película, en Plaza Colón', 1986, 'Cine', 'Paula', 'Ese enero nos alojábamos a dos cuadras de Plaza Colón, en Mar del Plata. Una noche salimos del cine y nos quedamos en un banco de la plaza, con los abrigos encima de las rodillas, discutiendo el final de Volver al futuro. Mi primo juraba que algún día los autos iban a volar. Mamá nos compró maní y dejamos que hablara hasta terminar la bolsita. No me acuerdo de la sala, pero sí de esa conversación.'],
  ['bariloche', 'El capítulo que contamos en el Centro Cívico', 1989, 'Televisión', 'Nico', 'En nuestro primer viaje a Bariloche, mi hermana tenía miedo de perderse su programa de la tarde. Durante la parada en el Centro Cívico, papá hizo de narrador e inventó un capítulo con nosotros como protagonistas. La torre del reloj era un castillo y el lago, un lugar secreto. Nos sacó una foto actuando frente a los arcos. Terminamos olvidándonos de pedir que prendieran la tele en el hotel.'],
  ['salta', 'Tres intentos bajo los árboles de la plaza', 1984, 'Videojuegos', 'Ana', 'Mi primo vino de visita a Salta con una maquinita electrónica de un solo juego. La llevó a la Plaza 9 de Julio después del almuerzo. Elegimos un banco a la sombra, frente al Cabildo, porque al sol no se veía la pantalla. Anotábamos los puntajes en el reverso de un boleto y cada uno tenía tres intentos. Mi abuela nos encontró ahí dos horas después: no habíamos caminado ni una cuadra.'],
  ['buenosaires', 'La ronda de mate del Parque Centenario', 1997, 'Personales', 'Lucía', 'Nos encontrábamos los sábados a las cinco en la entrada del Parque Centenario por la avenida Díaz Vélez, cerca del museo. Yo iba desde Almagro en una bici verde; Juli llevaba el termo y Mariano siempre aparecía con galletitas rotas en la mochila. Dábamos una vuelta al lago y elegíamos el mismo pedazo de pasto para sentarnos. Una tarde nos agarró la lluvia y volvimos pedaleando, con el mate guardado en una bolsa. Todavía tengo la foto que nos sacamos empapados en el palier.'],
  ['rosario', 'Una cinta y las escalinatas del Monumento', 1993, 'Música', 'Fede', 'Con mi amigo Martín terminamos la secundaria y nos regalamos un cassette grabado por cada uno. Nos juntamos a intercambiarlos en las escalinatas del Monumento a la Bandera, mirando hacia el Paraná. El suyo empezaba con rock nacional y tenía una lista escrita con birome azul. Escuchamos un lado entero compartiendo auriculares, mientras comíamos bizcochitos. En la etiqueta del mío puso “Rosario, diciembre del 93”. Lo conservé aunque después dejé de tener dónde escucharlo.'],
  ['cordoba', 'La plaza antes del primer viaje solos', 1995, 'Lugares', 'Sole', 'Quedamos en la Plaza San Martín de Córdoba para organizar nuestro primer viaje a las sierras sin los grandes. Nos sentamos en un banco frente a la Catedral con un mapa de papel y una libreta para sumar los gastos. Teníamos plata para el pasaje y muy poco más. Terminamos eligiendo llevar comida desde casa y repartir las bolsas. Cada vez que vuelvo a esa plaza me acuerdo de lo importante que nos sentíamos haciendo las cuentas.'],
  ['mendoza', 'Los diez años de Sofi al lado del lago', 1998, 'Acontecimientos', 'Diego', 'Mi hermana cumplió diez y pidió festejar en el Parque General San Martín, cerca del lago. Fuimos temprano a Mendoza a buscar sombra; mi viejo llevó las sillas plegables y yo me encargué de inflar quince globos amarillos. Armamos una búsqueda del tesoro con pistas escritas a mano. El premio estaba en la conservadora, debajo de las gaseosas. En la foto final se ve a Sofi con la corona de cartulina y toda la boca pintada de merengue.'],
  ['mar', 'La lista del videoclub en una servilleta', 1996, 'Cine', 'Julieta', 'El departamento de vacaciones quedaba cerca de Plaza Colón, en Mar del Plata. Habíamos llevado la videocasetera porque anunciaban lluvia. El primer día nos sentamos en la plaza a escribir qué películas quería ver cada uno: mi hermano pidió Toy Story y mi papá una de aventuras. La lista quedó en una servilleta llena de arena. Al final vimos la misma cinta dos noches seguidas porque nos olvidamos de devolverla.'],
  ['bariloche', 'Una sitcom inventada en Bariloche', 1992, 'Televisión', 'Pablo', 'La foto de nuestro viaje de egresados se hizo en el Centro Cívico de Bariloche, debajo de los arcos. Mientras esperábamos a los que habían ido a comprar chocolate, empezamos a repartir personajes de una comedia de televisión inventada. El profe quedó como el vecino que se quejaba del ruido y actuó tan bien que nadie podía ponerse serio. El fotógrafo tuvo que esperar. La copia que guardé tiene nuestros nombres escritos atrás.'],
  ['salta', 'El récord de la Game Boy en Plaza 9 de Julio', 1999, 'Videojuegos', 'Mati', 'Llevé mi Game Boy a la Plaza 9 de Julio de Salta una tarde de las vacaciones de invierno. Nos sentamos cerca del Cabildo, donde daba el sol, con cuatro pilas de repuesto y una libreta para los récords. Mi prima, que decía que no sabía jugar, nos ganó a todos en Tetris. Le prometimos un helado si repetía la marca y lo hizo en la partida siguiente. Todavía me lo recuerda cada vez que nos vemos.'],
  ['buenosaires', 'La foto del Fotolog, junto al lago', 2007, 'Personales', 'Cami', 'Nos juntamos en el Parque Centenario después de rendir la última materia. Llevé una cámara digital plateada que usaba dos pilas y una tarjeta donde casi no quedaba espacio. Elegimos el lago de fondo y sacamos la misma foto ocho veces: siempre alguien cerraba los ojos. Esa noche subí una al Fotolog con un marco negro y un texto larguísimo. Mi mejor amiga comentó antes de que terminara de avisarle por Messenger.'],
  ['rosario', 'Un auricular cada uno frente al Paraná', 2005, 'Música', 'Agus', 'Después de mi primera entrevista de trabajo fui con mi novia al Monumento a la Bandera. Nos sentamos en la parte baja de las escalinatas, mirando el Paraná. En mi MP3 de 128 MB entraban pocas canciones, así que las conocíamos de memoria. Compartimos los auriculares y una gaseosa tibia mientras le contaba todas las cosas que creía haber contestado mal. A la semana me llamaron. Para festejar volvimos al mismo lugar.'],
  ['cordoba', 'Nos encontramos antes de conectarnos', 2004, 'Lugares', 'Flor', 'Mis amigas y yo quedamos en la Plaza San Martín de Córdoba para intercambiar las fotos de una salida del colegio. Llevé las copias impresas en un sobre de laboratorio; algunas tenían los dedos tapando el lente. Nos repartimos las mejores junto a la Catedral y prometimos escanear las otras. Esa noche la conversación siguió por Messenger: cada una se puso una foto distinta y nos mandamos zumbidos hasta que nos mandaron a dormir.'],
  ['mendoza', 'El reencuentro del curso en el parque', 2009, 'Acontecimientos', 'Juan', 'Armamos un grupo para reencontrarnos cinco años después de terminar el colegio. Elegimos el lago del Parque General San Martín, en Mendoza, porque todos sabíamos llegar. Cada uno llevó algo para el picnic; yo aparecí con el álbum de la fiesta de egresados. Nos pasamos las fotos de mano en mano y repetimos una, en el mismo orden en que estábamos en el colegio. Esta vez entramos todos en el encuadre.'],
  ['mar', 'El día que cambiamos playa por Shrek', 2002, 'Cine', 'Vero', 'Salimos del departamento con la sombrilla y llegamos hasta Plaza Colón, en Mar del Plata, antes de que empezara a llover. Nos refugiamos con mis primos y decidimos volver a buscar una película para la tarde. Terminamos viendo Shrek, que habíamos conseguido en video, sentados en colchones en el living. Afuera seguía lloviendo; adentro repartíamos pochoclos en tazas porque no había suficientes bowls. Fue el día de vacaciones que más recordamos.'],
  ['bariloche', 'Una portada de serie en el Centro Cívico', 2006, 'Televisión', 'Nacho', 'Viajamos a Bariloche con mis hermanos y nos pasamos el trayecto inventando teorías sobre Lost. En el Centro Cívico quisimos sacar una foto como si fuera la portada de nuestra propia serie: caras serias, brazos cruzados y las montañas de fondo. Mi mamá nos cortó los pies en la primera toma. En la segunda se metió papá saludando. Terminamos imprimiendo esa y poniéndole un título con marcador.'],
  ['salta', 'Una consola, cuatro turnos y un helado', 2008, 'Videojuegos', 'Luli', 'Mi hermano estrenó una consola portátil durante las vacaciones en Salta. A la tarde la llevamos a la Plaza 9 de Julio y buscamos un banco frente al Cabildo. Éramos cuatro, así que el que perdía entregaba la consola y elegía quién seguía. La batería se terminó justo cuando estaba por pasar un nivel. Guardamos todo, fuimos a buscar helado y al volver al hotel lo primero que hicimos fue enchufar el cargador.'],
];
export const initialMemories: Memory[] = scenes.map(([location, title, year, category, author, description], index) => ({ ...locations[location], id: `demo-${index}`, title, year, category, author, description, source: 'demo' }));
export const eraContent: Record<Decade, { label: string; description: string }> = {
  1980: { label: 'Los ochenta', description: 'Cassettes, cámaras con rollo y tardes que parecían no terminar.' },
  1990: { label: 'Los noventa', description: 'Videoclubes, pilas de repuesto y encuentros sin mensajes de aviso.' },
  2000: { label: 'Los dos mil', description: 'Fotos digitales, zumbidos y canciones que entraban en el bolsillo.' },
};
